trigger: 'none' # will disable CI builds entirely

pool:
  vmImage: ubuntu-latest
    
variables:
  BuildConfiguration: release

stages:
- stage: BuildStage
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
  
    steps:

    - task: UseDotNet@2
      displayName: Install .NET 6 sdk
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: Restore Nuget Packages
      inputs:
        command: restore
        projects: '**/WebApp.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build Web App
      inputs:
        projects: '**/WebApp.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests
      inputs:
        command: test
        projects: '**/*UnitTest*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Create Web App Package (.zip)
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact (WebApp.zip)'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: DeployStage
  displayName: 'Deploy Stage'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'AzureDevOps(072c1136-ad60-4101-bdf4-e28f1f37a213)'
        appType: 'webApp'
        WebAppName: 'dotnetcore-mvc'
        packageForLinux: '$(build.artifactstagingdirectory)/**/*.zip'